# Generated by Django 3.0.3 on 2020-09-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cifar10',
            new_name='Model_image',
        ),
    ]
