# Generated by Django 3.0.3 on 2020-09-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0003_model_image_object_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_image',
            name='object_class',
        ),
    ]
